[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir=../../ --theme=repo"

[context.production.environment]
HUGO_VERSION = "0.76.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
