name = "Hugo Bootstrap Theme"
license = "MIT"
licenselink = "https://github.com/razonyang/hugo-theme-bootstrap/blob/master/LICENSE"
description = "A clean, responsive and feature-rich blog theme for Hugo"
homepage = "https://github.com/razonyang/hugo-theme-bootstrap"
tags = [
  "bootstrap",
  "clean",
  "simple",
  "blog",
  "responsive",
  "feature-rich",
  "mobile",
  "fast",
  "search",
  "multilingual"
]
features = [
  "hooks",
  "i18n",
  "comments",
  "breadcrumb",
  "search"
]
min_version = "0.76.0"
[author]
  name = "Razon Yang"
  homepage = "https://razonyang.com"
