[[main]]
  name = "主页"
  url = "/"
  pre = '<i class="fas fa-fw fa-home"></i> '
  weight = 10

[[main]]
  name = "归档"
  url = "/archives/"
  pre = '<i class="fas fa-fw fa-file-archive"></i> '
  weight = 20

[[main]]
  name = "分类"
  url = "/categories/"
  pre = '<i class="fas fa-fw fa-folder"></i> '
  weight = 30

[[main]]
  name = "标签"
  url = "/tags/"
  pre = '<i class="fas fa-fw fa-tags"></i> '
  weight = 40

[[main]]
  name = "关于"
  url = "/about/"
  pre = '<i class="fas fa-fw fa-info-circle"></i> '
  weight = 50

[[main]]
  name = "下拉菜单"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "外部链接"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  pre = '<i class="fas fa-fw fa-external-link-alt"></i> '
