[[main]]
  name = "Home"
  url = "/"
  pre = '<i class="fas fa-fw fa-home"></i> '
  weight = 10

[[main]]
  name = "Archives"
  url = "/archives/"
  pre = '<i class="fas fa-fw fa-file-archive"></i> '
  weight = 20

[[main]]
  name = "Categories"
  url = "/categories/"
  pre = '<i class="fas fa-fw fa-folder"></i> '
  weight = 30

[[main]]
  name = "Tags"
  url = "/tags/"
  pre = '<i class="fas fa-fw fa-tags"></i> '
  weight = 40

[[main]]
  name = "About"
  url = "/about/"
  pre = '<i class="fas fa-fw fa-info-circle"></i> '
  weight = 50

[[main]]
  name = "Dropdown"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "External"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  pre = '<i class="fas fa-fw fa-external-link-alt"></i> '
