[[main]]
  name = "歸檔"
  url = "/archives/"
  pre = '<i class="fas fa-fw fa-file-archive"></i> '
  weight = 20

[[main]]
  name = "關於"
  url = "/about/"
  pre = '<i class="fas fa-fw fa-info-circle"></i> '
  weight = 50

[[main]]
  name = "下拉菜單"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "外部鏈接"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  pre = '<i class="fas fa-fw fa-external-link-alt"></i> '
