[[main]]
  name = "Archives"
  url = "/archives/"
  pre = '<i class="fas fa-fw fa-file-archive"></i> '
  weight = 20

[[main]]
  name = "About"
  url = "/about/"
  pre = '<i class="fas fa-fw fa-info-circle"></i> '
  weight = 50

[[main]]
  name = "Dropdown"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "External"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  pre = '<i class="fas fa-fw fa-external-link-alt"></i> '
