[[main]]
  name = "Dropdown"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "External"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  pre = '<i class="fas fa-fw fa-external-link-alt"></i> '
