# mainSections = ["post", "posts"] # Default to ["posts"].

author = "Razon Yang"
# titleSeparator = "|" # Title separator. Default to "-".

description = "An extreme fast, responsive and feature-rich blog theme for Hugo"
# image = ["site-feature-image.jpg"]

# logo = "images/logo.png" # Logo image. Default to "images/logo.webp".
brand = "BOOTSTRAP"
# menusPosition = "left" # Menus position: right(default), left or center.

palette = "blue-gray" # Default palette. Optional.
# palettes = ["blue", "blue gray", "brown", "gray"] # Available palettes. Default to ALL.

# fullWidth = true # Full width.

# dateFormat = "Jan 2, 2006"

# Google Adsense
googleAdsense = ""

# math = true # Enable math globally.

# poweredBy = false # Whether to show powered by.

# featuredPostCount = 5 # The number of featured posts shown in sidebar.
# recentPostCount = 5 # The number of recent posts shown in sidebar.
# relatedPostCount = 5 # The number of related posts.
# categoryCount = 10 # The number of categories shown in sidebar.
# tagCount = 10 # The number of tags shown in sidebar.

# Custom CSS and JS
customCSS = []
customJS = []

[archive]
  paginate = 5 # Archive pagination. Default to 100.
  # dateFormat = "01-02" # Archive date format. Default to "Jan 2".

[analytics]
  # baidu = "" # Baidu Analytics

# Site verification
[siteVerification]
  google = ""
  bing = ""
  baidu = ""

[utterances]
  #repo = "razonyang/hugo-theme-bootstrap"
  #issueTerm = "pathname" # pathname, url, title, og:title
  #label = "comment"
  #theme = "github-light" # github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.

[search]
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    # isCaseSensitive = false
    # minMatchCharLength = 1
    threshold = 0.1
    # distance = 100
    # useExtendedSearch = true
