email = "user@domain.tld"
facebook = "facebookusername"
github = "githubusername"
gitlab = "gitlabusername"
linkedin = "linkedinusername"
stackoverflow = "stackoverflowuserid"
twitter = "twitterusername"
weibo = "weibousername"
zhihu = "zhihuusername"
